language: ruby
rvm: 
    # tested all on versions that work on heroku:
    # https://devcenter.heroku.com/articles/ruby-support#ruby-versions
    - 2.0.0
    - 2.1.7
    - 2.2.3
    - 2.3.0
install: bundle install
script: rake test
notifications:
    email: 
        on_success: never
        on_failure: always # the default, but good to mark here
